require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
  pod 'RevenuecatPurchasesCapacitorUi', :path => '../../node_modules/@revenuecat/purchases-capacitor-ui'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
  # Patch PurchasesPlugin.swift: presentCodeRedemptionSheet() indisponible sur Mac Catalyst
  plugin_file = File.join(__dir__, '../../node_modules/@revenuecat/purchases-capacitor/ios/Sources/RevenuecatPurchasesCapacitor/PurchasesPlugin.swift')
  if File.exist?(plugin_file)
    content = File.read(plugin_file)
    unless content.include?('#if !targetEnvironment(macCatalyst)')
      patched = content.gsub(
        /^(\s*)(.*presentCodeRedemptionSheet\(\).*)$/,
        "\\1#if !targetEnvironment(macCatalyst)\n\\1\\2\n\\1#endif"
      )
      File.write(plugin_file, patched)
      puts 'Patched presentCodeRedemptionSheet for Mac Catalyst'
    end
  end
end
